/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StreetPhotographyImport } from './routes/street-photography'
import { Route as FamilyPhotosImport } from './routes/family-photos'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StreetPhotographyRoute = StreetPhotographyImport.update({
  id: '/street-photography',
  path: '/street-photography',
  getParentRoute: () => rootRoute,
} as any)

const FamilyPhotosRoute = FamilyPhotosImport.update({
  id: '/family-photos',
  path: '/family-photos',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/family-photos': {
      id: '/family-photos'
      path: '/family-photos'
      fullPath: '/family-photos'
      preLoaderRoute: typeof FamilyPhotosImport
      parentRoute: typeof rootRoute
    }
    '/street-photography': {
      id: '/street-photography'
      path: '/street-photography'
      fullPath: '/street-photography'
      preLoaderRoute: typeof StreetPhotographyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/family-photos': typeof FamilyPhotosRoute
  '/street-photography': typeof StreetPhotographyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/family-photos': typeof FamilyPhotosRoute
  '/street-photography': typeof StreetPhotographyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/family-photos': typeof FamilyPhotosRoute
  '/street-photography': typeof StreetPhotographyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/family-photos'
    | '/street-photography'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/family-photos' | '/street-photography'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/family-photos'
    | '/street-photography'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FamilyPhotosRoute: typeof FamilyPhotosRoute
  StreetPhotographyRoute: typeof StreetPhotographyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FamilyPhotosRoute: FamilyPhotosRoute,
  StreetPhotographyRoute: StreetPhotographyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/family-photos",
        "/street-photography"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/family-photos": {
      "filePath": "family-photos.tsx"
    },
    "/street-photography": {
      "filePath": "street-photography.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
