name: Deploy

on:
  push: 
    branches: [ live ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /www/family-site-reactjs
            git pull origin live
            npm install
            npm run build
